service:
  name: slstack

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  
functions:
  openDoor:
    handler: src/handlers/openDoor.handler
    events:
      - http:
          method: POST
          path: /openDoor
  kin:
    handler: src/handlers/kin.handler
    events:
      - http:
          method: POST
          path: /kin

custom:
  bundle:
    linting: false